/* Copyright © 2017 Oracle and/or its affiliates. All rights reserved. */
/* INSERT DATA IN TABLES AS MOVIE_USR commit when done */
INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENRE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name1',2006, 'studio1', 'genre1', 'rating1', 120, 'director1', 'description1');

INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENRE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name2',2007, 'studio2', 'genre2', 'rating2', 120, 'director2', 'description2');

INSERT INTO MOVIES(MOVIEID, MOVIENAME, YEAR, STUDIO, GENRE, RATING, RUNTIME, DIRECTOR, MOVIEDESCRIPTION) 
VALUES (MOVIES_SEQ.NEXTVAL, 'name3',2008, 'studio3', 'genre3', 'rating3', 120, 'director3', 'description3');

SELECT * FROM MOVIES;

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name1', 4, 'date1', 'description1');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name2', 4, 'date2', 'description2');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 100, 'name3', 4, 'date3', 'description3');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name4', 4, 'date4', 'description4');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name5', 4, 'date5', 'description5');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 101, 'name6', 4, 'date6', 'description6');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name7', 4, 'date7', 'description7');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name8', 4, 'date8', 'description8');

INSERT INTO REVIEWS(REVIEWID, MOVIEID, REVIEWERNAME, SCORE,REVIEWDATE, REVIEWDESCRIPTION)
VALUES (REVIEWS_SEQ.NEXTVAL, 102, 'name9', 4, 'date9', 'description9');

SELECT * FROM REVIEWS;

COMMIT;
